### ISSUE TITLE
 The audio files are getting distorted afterd download, resulting in different md5sum

### ISSUE THREAD

**Issue by venorest** [black-06/grpc-gateway-file#1]
When I attempt to download an MP3 audio file, it becomes corrupted, exhibiting distortion noises. Upon checking the md5 checksums of the files, I found them to be different.

**Comment by black-06** [comment]
I downloaded a mp3 using [examples](https://github.com/black-06/grpc-gateway-file/tree/master/examples),  their md5 is the same. Would you provide more information?
