### ISSUE TITLE
WithHTTPBodyMarshaler & UnmarshalOptions

### ISSUE THREAD

**Issue by n-r-w** [black-06/grpc-gateway-file#17]
Hi! In WithHTTPBodyMarshaler you're using DiscardUnknown=true. This causes grpc_gateway to stop checking the enums. Is there any need for this option?

**Comment by n-r-w** [comment]
In any case I suggest to use "multipart/form-data" instead of "*" in runtime.WithMarshalerOption.

**Comment by n-r-w** [comment]
In this method, grpc_gateway select marshaler according content type:
![image](https://github.com/black-06/grpc-gateway-file/assets/38435980/c9a62650-3f0f-4915-b47a-f61ce5fc1d12)

**Comment by n-r-w** [comment]
And one more question. I don't see any way to limit the size of incoming files. I.e., you can upload a file of any size and thereby kill the server.

**Comment by black-06** [comment]
> Hi! In WithHTTPBodyMarshaler you're using DiscardUnknown=true. This causes grpc_gateway to stop checking the enums. Is there any need for this option?

It's consistent with grpc-gateway. See [defaultMarshaler](https://github.com/grpc-ecosystem/grpc-gateway/blob/main/runtime/marshaler_registry.go)

**Comment by black-06** [comment]
> In any case I suggest to use "multipart/form-data" instead of "*" in runtime.WithMarshalerOption.

I agree

**Comment by black-06** [comment]
> And one more question. I don't see any way to limit the size of incoming files. I.e., you can upload a file of any size and thereby kill the server.

Do you have any suggestions on this?

**Comment by n-r-w** [comment]
> > And one more question. I don't see any way to limit the size of incoming files. I.e., you can upload a file of any size and thereby kill the server.
> 
> Do you have any suggestions on this?

I will see today, because without this restriction, it's too dangerous to use in production.

**Comment by n-r-w** [comment]
https://github.com/black-06/grpc-gateway-file/pull/18

**Comment by n-r-w** [comment]
@black-06 Could you look at the merge request?
