### ISSUE TITLE
Problem with processing two or more files

### ISSUE THREAD

**Issue by Steshoff** [black-06/grpc-gateway-file#2]
Hello. When processing two or more files I get an error: "parse multipart form failed multipart: NextPart: EOF". Could you please tell me if it is possible to process two or more files? In your MultipartFormHeader method I am not sure about the logic and the possibility of working with multiple files. This library is convenient, but if there is a possibility, please clarify this point. Thank you.
 ```
func MultipartFormHeader(server UploadServer, key string) (*multipart.FileHeader, error) {

	form, err := ParseMultipartForm(server)
	if err != nil {
		return nil, errors.Wrapf(err, "parse multipart form failed")
	}
	if headers := form.File[key]; len(headers) > 0 {
		return headers[0], nil
	}
	return nil, http.ErrMissingFile

 }

**Comment by black-06** [comment]
I think it can. It's probably a bug. I'll check it and let you know.

**Comment by black-06** [comment]
Yes, `MultipartFormHeader` is not suitable for multiple files, please use `ParseMultipartForm ` instead.
I updated an example in https://github.com/black-06/grpc-gateway-file/commit/bf51eefbf32f65566310af445763a7bc5caea7a8.

Thanks for your feedback
